### ISSUE TITLE
KafkaJolokia Should be the Only Compatibility

### ISSUE THREAD

**Issue by dgeorg42** [netuitive-community-packages/netuitive-packages-kafka#4]
@Createor - Thanks for correcting the compatibility mistakes I had in some of the _package.json_ files. For Kafka, however, the compatibility should actually be ONLY for KafkaJolokia. The metric names are completely different between the old collector (Kafka) and the new collector (KafkaJolokia) and the package is built specifically for the new.

**Comment by Grumblesmith** [comment]
Thanks for the clarification @dgeorg42 . I'll push out that update shortly.
